language: node_js
node_js:
  - 12
  - 14
  - 16
addons:
  code_climate:
    repo_token: 97e0787cf70c2aa71def007ff75bce222b6622a6bf2e7c09a2bb41d0bfa8089c
after_script:
  - npm run lcov
  - cat coverage/lcov.info | node_modules/.bin/codeclimate-test-reporter
